### ISSUE TITLE
update

### ISSUE THREAD

**Issue by nhonhoem0166** [barbarbar338/bh-open-api-webpage#1]
Please update https://www.brawlhalla.com/rankings/brawlball/

Thank you so much for what you do <3

**Comment by barbarbar338** [comment]
I hadn't thought of it, thanks for the warning :) i'll integrate it asap

**Comment by barbarbar338** [comment]
I added the feature you requested. You can see seasonal ranked data with this endpoint: https://brawlhalla-api.herokuapp.com/v1/utils/rankedseasonal

Here is an example: https://brawlhalla-api.herokuapp.com/v1/utils/rankedseasonal?region=eu&page=1
