### ISSUE TITLE
The URL to get the hero images is incorrect.

### ISSUE THREAD

**Issue by JuanPabloRP** [barbarbar338/bh-open-api-webpage#4]
Example: 

Doesn't work:
https://www.brawlhalla.com/c/uploads/2021/07/bodvar.png

Works:
https://cms.brawlhalla.com/c/uploads/2021/07/bodvar.png

**Comment by barbarbar338** [comment]
I'll create a commit fixes this rn, thanks for the report! :)

**Comment by barbarbar338** [comment]
Fixed with the latest deployment. You can now use it again with all the correct images. Also added the latest legends too!
